!SESSION 2015-03-12 13:55:45.043 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_75
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product

!ENTRY org.eclipse.cdt.core 1 0 2015-03-12 13:56:39.137
!MESSAGE Indexed 'UnqliteTest' (2 sources, 219 headers) in 11,6 sec: 24 844 declarations; 88 039 references; 0 unresolved inclusions; 0 syntax errors; 2 unresolved names (0,0018 %)

!ENTRY org.eclipse.cdt.core 1 0 2015-03-12 13:56:44.124
!MESSAGE Indexed 'PlayBeat' (12 sources, 233 headers) in 4,96 sec: 19 643 declarations; 36 343 references; 0 unresolved inclusions; 0 syntax errors; 29 unresolved names (0,052 %)

!ENTRY org.eclipse.cdt.dsf.gdb 4 5012 2015-03-12 13:59:43.732
!MESSAGE Error in final launch sequence
!STACK 1
org.eclipse.core.runtime.CoreException: Failed to execute MI command:
source /home/maeln/.gdb/.gdbinit
Error message from debugger back end:
/home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
	at org.eclipse.cdt.dsf.concurrent.Query.get(Query.java:115)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugSession(GdbLaunchDelegate.java:235)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugger(GdbLaunchDelegate.java:109)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launch(GdbLaunchDelegate.java:97)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.Exception: /home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:926)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:755)
!SUBENTRY 1 org.eclipse.cdt.dsf.gdb 4 10004 2015-03-12 13:59:43.733
!MESSAGE Failed to execute MI command:
source /home/maeln/.gdb/.gdbinit
Error message from debugger back end:
/home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
!STACK 0
java.lang.Exception: /home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:926)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:755)

!ENTRY org.eclipse.cdt.dsf.gdb 4 5012 2015-03-12 14:02:41.740
!MESSAGE Error in final launch sequence
!STACK 1
org.eclipse.core.runtime.CoreException: Failed to execute MI command:
source /home/maeln/.gdb/.gdbinit
Error message from debugger back end:
/home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
	at org.eclipse.cdt.dsf.concurrent.Query.get(Query.java:115)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugSession(GdbLaunchDelegate.java:235)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugger(GdbLaunchDelegate.java:109)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launch(GdbLaunchDelegate.java:97)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.Exception: /home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:926)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:755)
!SUBENTRY 1 org.eclipse.cdt.dsf.gdb 4 10004 2015-03-12 14:02:41.740
!MESSAGE Failed to execute MI command:
source /home/maeln/.gdb/.gdbinit
Error message from debugger back end:
/home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
!STACK 0
java.lang.Exception: /home/maeln/.gdb/.gdbinit:6: Error in sourced command file:\nError while executing Python code.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:926)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:755)

!ENTRY org.eclipse.cdt.core 4 0 2015-03-12 15:02:34.855
!MESSAGE Error: Cannot run program "perf": Unknown reason
!STACK 0
java.io.IOException: Cannot run program "perf": Unknown reason
	at org.eclipse.cdt.utils.spawner.Spawner.exec(Spawner.java:349)
	at org.eclipse.cdt.utils.spawner.Spawner.<init>(Spawner.java:91)
	at org.eclipse.cdt.utils.spawner.ProcessFactory.exec(ProcessFactory.java:91)
	at org.eclipse.cdt.core.CommandLauncher.execute(CommandLauncher.java:194)
	at org.eclipse.linuxtools.internal.profiling.launch.LocalLauncher.execute(LocalLauncher.java:38)
	at org.eclipse.linuxtools.tools.launch.core.factory.RuntimeProcessFactory.exec(RuntimeProcessFactory.java:294)
	at org.eclipse.linuxtools.tools.launch.core.factory.RuntimeProcessFactory.exec(RuntimeProcessFactory.java:239)
	at org.eclipse.linuxtools.tools.launch.core.factory.RuntimeProcessFactory.exec(RuntimeProcessFactory.java:187)
	at org.eclipse.linuxtools.tools.launch.core.factory.RuntimeProcessFactory.exec(RuntimeProcessFactory.java:172)
	at org.eclipse.linuxtools.internal.perf.PerfCore.checkPerfInPath(PerfCore.java:237)
	at org.eclipse.linuxtools.internal.perf.launch.PerfLaunchConfigDelegate.launch(PerfLaunchConfigDelegate.java:67)
	at org.eclipse.linuxtools.internal.profiling.launch.provider.launch.ProviderLaunchConfigurationDelegate.launch(ProviderLaunchConfigurationDelegate.java:88)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.linuxtools.perf 4 0 2015-03-12 15:02:34.857
!MESSAGE Error: Perf was not found on PATH

!ENTRY org.eclipse.core.jobs 4 2 2015-03-12 15:04:38.954
!MESSAGE An internal error occurred during: "Launching PlayBeat Release".
!STACK 0
java.lang.IllegalArgumentException: invalid version "": invalid format
	at org.osgi.framework.Version.<init>(Version.java:147)
	at org.eclipse.linuxtools.internal.perf.PerfCore.getPerfVersion(PerfCore.java:231)
	at org.eclipse.linuxtools.internal.perf.launch.PerfLaunchConfigDelegate.launch(PerfLaunchConfigDelegate.java:95)
	at org.eclipse.linuxtools.internal.profiling.launch.provider.launch.ProviderLaunchConfigurationDelegate.launch(ProviderLaunchConfigurationDelegate.java:88)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at org.osgi.framework.Version.<init>(Version.java:126)
	... 8 more
